### PR TITLE
TLS support

### PR DESCRIPTION
**Pull request by bruceesmith**
### Support of memcached TLS

Add support for the (experimental) TLS feature of memcached [TLS](https://github.com/memcached/memcached/wiki/TLS)

Function NewWithTLS(config *tls.Config, server ...string) *Client is added. Simply pass in a *tls.Config whose settings match those of the memcached daemon, then all other methods of gomemcache operate identically to those of the normal (non-TLS) case.

### CODE REVIEW

**Comment by bruceesmith** [comment]
> @googlebot I signed it!

**Comment by bruceesmith** [comment]
@googlebot I signed it!

**Comment by QuChen88** [comment]
@bradfitz Ping. Can you please take a look at this and maybe merge it? 

It will be great to have TLS support for this client.

**Comment by bradfitz** [comment]
I'd prefer a new exported field on Client, not a new constructor.

Also, each server shard might have its own hostname/tls.Config. The option on Client should be more like `TLSConfigForerver func(target string) (_ *tls.Config, ok bool)` probably.

Ideally there would be tests too. I tried to run it against memcached built with TLS enabled and I couldn't even get memcached on Debian stable to work. (I'm surprised it'd need anything newer, so I was likely holding it wrong but then ran out of time.)

**Comment by bradfitz** [comment]
> Ideally there would be tests too. I tried to run it against memcached built with TLS enabled and I couldn't even get memcached on Debian stable to work. (I'm surprised it'd need anything newer, so I was likely holding it wrong but then ran out of time.)

I've addressed this part. This package now has better tests & GitHub Actions CI hooked up.

**Comment by bruceesmith** [comment]
I'm very sorry @bradfitz and @QuChen88, I just don't have the hours in my day at present to adjust my PR based on Brad's comments .........

**Comment by bradfitz** [comment]
Turns out we don't actually need this since #158, @bruceesmith. That hook already provides everything necessary to do TLS dials.

I sent #169 to add a test & mention in the docs.

**Pull request closed without merging**
